// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types {
    export type MessageDTO = {
        "content": string;
        "from": string;
        "date": string;
    };
    export type UserDTO = {
        "userID": string;
        "name": string;
        "email": string;
        "avatar": string;
    };
    export type RoomDTO = {
        "roomID": string;
        "name": string;
    };
    export type VoteDTO = {
        "userID": string;
        "score": string;
    };
    export type RoundDTO = {
        "name": string;
        "votes": (types.VoteDTO)[];
    };
    export type CurrentRoundDTO = {
        "name": string;
        "flipped": boolean;
    };
    export type AckResult = ({
        "type": "OK";
    } | ({
        "type": "Error";
    } & {
        "error": string;
    }));
}
