// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types {
    export type MessageDTO = {
        "content": string;
        "from": string;
        "date": string;
    };
    export type UserDTO = {
        "userID": string;
        "username": string;
    };
}
