// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CurrentRoundDTO { name: string, flipped: boolean, candidates: Array<string>, max_votes: number, anonymous: boolean, round_type: string, }