// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoteDTO } from "./VoteDTO";

export interface RoundDTO { name: string, votes: Array<VoteDTO>, }